# Generated by Django 4.1.3 on 2022-11-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.IntegerField()),
                ('ra', models.IntegerField()),
                ('curso', models.CharField(choices=[('EC', 'Engenharia de Computação'), ('ES', 'Engenharia de Software'), ('EL', 'Engenharia Elétrica'), ('EE', 'Engenharia Eletrônica'), ('EM', 'Engenharia Mecânica'), ('MA', 'Matemática'), ('AS', 'Análise e Desenvolvimento de Sistemas')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cpf', models.IntegerField()),
                ('funcao', models.CharField(choices=[('AT', 'Atendente'), ('NT', 'Nutricionista'), ('GR', 'Gerente')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('peso_gramas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('periodo', models.CharField(choices=[('A', 'Almoço'), ('J', 'Jantar')], max_length=1)),
                ('cardapio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.cardapio')),
                ('estudante', models.ManyToManyField(to='meals.estudante')),
            ],
        ),
        migrations.AddField(
            model_name='cardapio',
            name='acompanhamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhamento', to='meals.itemestoque'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='nutricionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.funcionario'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='prato_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prato_principal', to='meals.itemestoque'),
        ),
        migrations.AddField(
            model_name='cardapio',
            name='sobremesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.itemestoque'),
        ),
    ]
