# Generated by Django 4.1.3 on 2022-11-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_refeicao_dia_da_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicao',
            name='estudante',
            field=models.ManyToManyField(blank=True, null=True, to='meals.estudante'),
        ),
    ]
