# Generated by Django 4.1.3 on 2022-12-10 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_remove_refeicao_dia_da_semana_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardapio',
            options={'verbose_name_plural': 'Cardápios'},
        ),
        migrations.AlterModelOptions(
            name='estudante',
            options={'verbose_name_plural': 'Estudantes'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name_plural': 'Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='itemestoque',
            options={'verbose_name_plural': 'Itens no Estoque'},
        ),
        migrations.AlterModelOptions(
            name='refeicao',
            options={'verbose_name_plural': 'Refeições'},
        ),
    ]
